server:
  port: 8080    # \u7AEF\u53E3\u53F7\u4E3A8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmanagesystem?
    username: root
    password: 15983044725
